-- rrk-shell Hyprland config. Split into files under config/ — this file only wires them together.
-- colors.lua is generated by matugen from the wallpaper (rrkshell wallpaper <img>); it is optional.
require("config/variables")
require("config/env")
require("config/monitors")
require("config/look")
pcall(require, "config/colors")
require("config/input")
require("config/rules")
require("config/autostart")
require("config/keybinds")
