hl.on("hyprland.start", function()
    hl.exec_cmd(shell .. " start")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("easyeffects --hide-window --service-mode")   -- equalizer backend for the media panel (service mode, no window)
end)
