-- generated by matugen from the current wallpaper — do not edit
hl.config({
  general = {
    col = {
      active_border   = "rgba({{colors.primary.default.hex_stripped}}ee)",
      inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}66)",
    },
  },
})
